/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivitiesRouteImport } from './routes/app.activities'
import { Route as AppAdmissionsRouteImport } from './routes/app.admissions'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAppraisalRouteImport } from './routes/app.appraisal'
import { Route as AppAssessmentPlanRouteImport } from './routes/app.assessment-plan'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppBehaviourRouteImport } from './routes/app.behaviour'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppCommunicationRouteImport } from './routes/app.communication'
import { Route as AppDayScheduleRouteImport } from './routes/app.day-schedule'
import { Route as AppEnrollmentRouteImport } from './routes/app.enrollment'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppFinalsRouteImport } from './routes/app.finals'
import { Route as AppGradebookRouteImport } from './routes/app.gradebook'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppQuarterResultsRouteImport } from './routes/app.quarter-results'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppRecordRouteImport } from './routes/app.record'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppSchemesRouteImport } from './routes/app.schemes'
import { Route as AppSectionsRouteImport } from './routes/app.sections'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppSurveysRouteImport } from './routes/app.surveys'
import { Route as AppTermRouteImport } from './routes/app.term'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppTimetableBuilderRouteImport } from './routes/app.timetable-builder'
import { Route as AppTimetableGridRouteImport } from './routes/app.timetable-grid'
import { Route as AppTransportRouteImport } from './routes/app.transport'
import { Route as AppGuardiansIndexRouteImport } from './routes/app.guardians.index'
import { Route as AppGuardiansGuardianIdRouteImport } from './routes/app.guardians.$guardianId'
import { Route as AppStudentsIndexRouteImport } from './routes/app.students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app.students.$studentId'
import { Route as AppTeachersIndexRouteImport } from './routes/app.teachers.index'
import { Route as AppTeachersInstructorIdRouteImport } from './routes/app.teachers.$instructorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAppraisalRoute = AppAppraisalRouteImport.update({
  id: '/appraisal',
  path: '/appraisal',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentPlanRoute = AppAssessmentPlanRouteImport.update({
  id: '/assessment-plan',
  path: '/assessment-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppBehaviourRoute = AppBehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppRoute,
} as any)
const AppDayScheduleRoute = AppDayScheduleRouteImport.update({
  id: '/day-schedule',
  path: '/day-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentRoute = AppEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFinalsRoute = AppFinalsRouteImport.update({
  id: '/finals',
  path: '/finals',
  getParentRoute: () => AppRoute,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppQuarterResultsRoute = AppQuarterResultsRouteImport.update({
  id: '/quarter-results',
  path: '/quarter-results',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordRoute = AppRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemesRoute = AppSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionsRoute = AppSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysRoute = AppSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppTermRoute = AppTermRouteImport.update({
  id: '/term',
  path: '/term',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableBuilderRoute = AppTimetableBuilderRouteImport.update({
  id: '/timetable-builder',
  path: '/timetable-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableGridRoute = AppTimetableGridRouteImport.update({
  id: '/timetable-grid',
  path: '/timetable-grid',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardiansIndexRoute = AppGuardiansIndexRouteImport.update({
  id: '/guardians/',
  path: '/guardians/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardiansGuardianIdRoute = AppGuardiansGuardianIdRouteImport.update({
  id: '/guardians/$guardianId',
  path: '/guardians/$guardianId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersIndexRoute = AppTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersInstructorIdRoute = AppTeachersInstructorIdRouteImport.update({
  id: '/teachers/$instructorId',
  path: '/teachers/$instructorId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/marks': typeof MarksRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/appraisal': typeof AppAppraisalRoute
  '/app/assessment-plan': typeof AppAssessmentPlanRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/behaviour': typeof AppBehaviourRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/chat': typeof AppChatRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/day-schedule': typeof AppDayScheduleRoute
  '/app/enrollment': typeof AppEnrollmentRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/finals': typeof AppFinalsRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/health': typeof AppHealthRoute
  '/app/library': typeof AppLibraryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quarter-results': typeof AppQuarterResultsRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/record': typeof AppRecordRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/schemes': typeof AppSchemesRoute
  '/app/sections': typeof AppSectionsRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/surveys': typeof AppSurveysRoute
  '/app/term': typeof AppTermRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/timetable-builder': typeof AppTimetableBuilderRoute
  '/app/timetable-grid': typeof AppTimetableGridRoute
  '/app/transport': typeof AppTransportRoute
  '/app/': typeof AppIndexRoute
  '/app/guardians/$guardianId': typeof AppGuardiansGuardianIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/teachers/$instructorId': typeof AppTeachersInstructorIdRoute
  '/app/guardians/': typeof AppGuardiansIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
  '/app/teachers/': typeof AppTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marks': typeof MarksRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/appraisal': typeof AppAppraisalRoute
  '/app/assessment-plan': typeof AppAssessmentPlanRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/behaviour': typeof AppBehaviourRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/chat': typeof AppChatRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/day-schedule': typeof AppDayScheduleRoute
  '/app/enrollment': typeof AppEnrollmentRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/finals': typeof AppFinalsRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/health': typeof AppHealthRoute
  '/app/library': typeof AppLibraryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quarter-results': typeof AppQuarterResultsRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/record': typeof AppRecordRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/schemes': typeof AppSchemesRoute
  '/app/sections': typeof AppSectionsRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/surveys': typeof AppSurveysRoute
  '/app/term': typeof AppTermRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/timetable-builder': typeof AppTimetableBuilderRoute
  '/app/timetable-grid': typeof AppTimetableGridRoute
  '/app/transport': typeof AppTransportRoute
  '/app': typeof AppIndexRoute
  '/app/guardians/$guardianId': typeof AppGuardiansGuardianIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/teachers/$instructorId': typeof AppTeachersInstructorIdRoute
  '/app/guardians': typeof AppGuardiansIndexRoute
  '/app/students': typeof AppStudentsIndexRoute
  '/app/teachers': typeof AppTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/marks': typeof MarksRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/appraisal': typeof AppAppraisalRoute
  '/app/assessment-plan': typeof AppAssessmentPlanRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/behaviour': typeof AppBehaviourRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/chat': typeof AppChatRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/day-schedule': typeof AppDayScheduleRoute
  '/app/enrollment': typeof AppEnrollmentRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/finals': typeof AppFinalsRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/health': typeof AppHealthRoute
  '/app/library': typeof AppLibraryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quarter-results': typeof AppQuarterResultsRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/record': typeof AppRecordRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/schemes': typeof AppSchemesRoute
  '/app/sections': typeof AppSectionsRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/surveys': typeof AppSurveysRoute
  '/app/term': typeof AppTermRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/timetable-builder': typeof AppTimetableBuilderRoute
  '/app/timetable-grid': typeof AppTimetableGridRoute
  '/app/transport': typeof AppTransportRoute
  '/app/': typeof AppIndexRoute
  '/app/guardians/$guardianId': typeof AppGuardiansGuardianIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/teachers/$instructorId': typeof AppTeachersInstructorIdRoute
  '/app/guardians/': typeof AppGuardiansIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
  '/app/teachers/': typeof AppTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/marks'
    | '/app/activities'
    | '/app/admissions'
    | '/app/alerts'
    | '/app/appraisal'
    | '/app/assessment-plan'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/behaviour'
    | '/app/calendar'
    | '/app/certificates'
    | '/app/chat'
    | '/app/classes'
    | '/app/communication'
    | '/app/day-schedule'
    | '/app/enrollment'
    | '/app/exams'
    | '/app/fees'
    | '/app/finals'
    | '/app/gradebook'
    | '/app/health'
    | '/app/library'
    | '/app/profile'
    | '/app/quarter-results'
    | '/app/quizzes'
    | '/app/record'
    | '/app/reports'
    | '/app/resources'
    | '/app/schemes'
    | '/app/sections'
    | '/app/security'
    | '/app/settings'
    | '/app/subjects'
    | '/app/surveys'
    | '/app/term'
    | '/app/timetable'
    | '/app/timetable-builder'
    | '/app/timetable-grid'
    | '/app/transport'
    | '/app/'
    | '/app/guardians/$guardianId'
    | '/app/students/$studentId'
    | '/app/teachers/$instructorId'
    | '/app/guardians/'
    | '/app/students/'
    | '/app/teachers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marks'
    | '/app/activities'
    | '/app/admissions'
    | '/app/alerts'
    | '/app/appraisal'
    | '/app/assessment-plan'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/behaviour'
    | '/app/calendar'
    | '/app/certificates'
    | '/app/chat'
    | '/app/classes'
    | '/app/communication'
    | '/app/day-schedule'
    | '/app/enrollment'
    | '/app/exams'
    | '/app/fees'
    | '/app/finals'
    | '/app/gradebook'
    | '/app/health'
    | '/app/library'
    | '/app/profile'
    | '/app/quarter-results'
    | '/app/quizzes'
    | '/app/record'
    | '/app/reports'
    | '/app/resources'
    | '/app/schemes'
    | '/app/sections'
    | '/app/security'
    | '/app/settings'
    | '/app/subjects'
    | '/app/surveys'
    | '/app/term'
    | '/app/timetable'
    | '/app/timetable-builder'
    | '/app/timetable-grid'
    | '/app/transport'
    | '/app'
    | '/app/guardians/$guardianId'
    | '/app/students/$studentId'
    | '/app/teachers/$instructorId'
    | '/app/guardians'
    | '/app/students'
    | '/app/teachers'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/marks'
    | '/app/activities'
    | '/app/admissions'
    | '/app/alerts'
    | '/app/appraisal'
    | '/app/assessment-plan'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/behaviour'
    | '/app/calendar'
    | '/app/certificates'
    | '/app/chat'
    | '/app/classes'
    | '/app/communication'
    | '/app/day-schedule'
    | '/app/enrollment'
    | '/app/exams'
    | '/app/fees'
    | '/app/finals'
    | '/app/gradebook'
    | '/app/health'
    | '/app/library'
    | '/app/profile'
    | '/app/quarter-results'
    | '/app/quizzes'
    | '/app/record'
    | '/app/reports'
    | '/app/resources'
    | '/app/schemes'
    | '/app/sections'
    | '/app/security'
    | '/app/settings'
    | '/app/subjects'
    | '/app/surveys'
    | '/app/term'
    | '/app/timetable'
    | '/app/timetable-builder'
    | '/app/timetable-grid'
    | '/app/transport'
    | '/app/'
    | '/app/guardians/$guardianId'
    | '/app/students/$studentId'
    | '/app/teachers/$instructorId'
    | '/app/guardians/'
    | '/app/students/'
    | '/app/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MarksRoute: typeof MarksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activities': {
      id: '/app/activities'
      path: '/activities'
      fullPath: '/app/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admissions': {
      id: '/app/admissions'
      path: '/admissions'
      fullPath: '/app/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appraisal': {
      id: '/app/appraisal'
      path: '/appraisal'
      fullPath: '/app/appraisal'
      preLoaderRoute: typeof AppAppraisalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessment-plan': {
      id: '/app/assessment-plan'
      path: '/assessment-plan'
      fullPath: '/app/assessment-plan'
      preLoaderRoute: typeof AppAssessmentPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/behaviour': {
      id: '/app/behaviour'
      path: '/behaviour'
      fullPath: '/app/behaviour'
      preLoaderRoute: typeof AppBehaviourRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communication': {
      id: '/app/communication'
      path: '/communication'
      fullPath: '/app/communication'
      preLoaderRoute: typeof AppCommunicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/day-schedule': {
      id: '/app/day-schedule'
      path: '/day-schedule'
      fullPath: '/app/day-schedule'
      preLoaderRoute: typeof AppDayScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enrollment': {
      id: '/app/enrollment'
      path: '/enrollment'
      fullPath: '/app/enrollment'
      preLoaderRoute: typeof AppEnrollmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finals': {
      id: '/app/finals'
      path: '/finals'
      fullPath: '/app/finals'
      preLoaderRoute: typeof AppFinalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gradebook': {
      id: '/app/gradebook'
      path: '/gradebook'
      fullPath: '/app/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quarter-results': {
      id: '/app/quarter-results'
      path: '/quarter-results'
      fullPath: '/app/quarter-results'
      preLoaderRoute: typeof AppQuarterResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/record': {
      id: '/app/record'
      path: '/record'
      fullPath: '/app/record'
      preLoaderRoute: typeof AppRecordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schemes': {
      id: '/app/schemes'
      path: '/schemes'
      fullPath: '/app/schemes'
      preLoaderRoute: typeof AppSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sections': {
      id: '/app/sections'
      path: '/sections'
      fullPath: '/app/sections'
      preLoaderRoute: typeof AppSectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/surveys': {
      id: '/app/surveys'
      path: '/surveys'
      fullPath: '/app/surveys'
      preLoaderRoute: typeof AppSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/term': {
      id: '/app/term'
      path: '/term'
      fullPath: '/app/term'
      preLoaderRoute: typeof AppTermRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable-builder': {
      id: '/app/timetable-builder'
      path: '/timetable-builder'
      fullPath: '/app/timetable-builder'
      preLoaderRoute: typeof AppTimetableBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable-grid': {
      id: '/app/timetable-grid'
      path: '/timetable-grid'
      fullPath: '/app/timetable-grid'
      preLoaderRoute: typeof AppTimetableGridRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transport': {
      id: '/app/transport'
      path: '/transport'
      fullPath: '/app/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guardians/': {
      id: '/app/guardians/'
      path: '/guardians'
      fullPath: '/app/guardians/'
      preLoaderRoute: typeof AppGuardiansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guardians/$guardianId': {
      id: '/app/guardians/$guardianId'
      path: '/guardians/$guardianId'
      fullPath: '/app/guardians/$guardianId'
      preLoaderRoute: typeof AppGuardiansGuardianIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/': {
      id: '/app/students/'
      path: '/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers/': {
      id: '/app/teachers/'
      path: '/teachers'
      fullPath: '/app/teachers/'
      preLoaderRoute: typeof AppTeachersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers/$instructorId': {
      id: '/app/teachers/$instructorId'
      path: '/teachers/$instructorId'
      fullPath: '/app/teachers/$instructorId'
      preLoaderRoute: typeof AppTeachersInstructorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAppraisalRoute: typeof AppAppraisalRoute
  AppAssessmentPlanRoute: typeof AppAssessmentPlanRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBehaviourRoute: typeof AppBehaviourRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppChatRoute: typeof AppChatRoute
  AppClassesRoute: typeof AppClassesRoute
  AppCommunicationRoute: typeof AppCommunicationRoute
  AppDayScheduleRoute: typeof AppDayScheduleRoute
  AppEnrollmentRoute: typeof AppEnrollmentRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppFinalsRoute: typeof AppFinalsRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppHealthRoute: typeof AppHealthRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuarterResultsRoute: typeof AppQuarterResultsRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppRecordRoute: typeof AppRecordRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSchemesRoute: typeof AppSchemesRoute
  AppSectionsRoute: typeof AppSectionsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppSurveysRoute: typeof AppSurveysRoute
  AppTermRoute: typeof AppTermRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppTimetableBuilderRoute: typeof AppTimetableBuilderRoute
  AppTimetableGridRoute: typeof AppTimetableGridRoute
  AppTransportRoute: typeof AppTransportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGuardiansGuardianIdRoute: typeof AppGuardiansGuardianIdRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppTeachersInstructorIdRoute: typeof AppTeachersInstructorIdRoute
  AppGuardiansIndexRoute: typeof AppGuardiansIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppTeachersIndexRoute: typeof AppTeachersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAppraisalRoute: AppAppraisalRoute,
  AppAssessmentPlanRoute: AppAssessmentPlanRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBehaviourRoute: AppBehaviourRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppChatRoute: AppChatRoute,
  AppClassesRoute: AppClassesRoute,
  AppCommunicationRoute: AppCommunicationRoute,
  AppDayScheduleRoute: AppDayScheduleRoute,
  AppEnrollmentRoute: AppEnrollmentRoute,
  AppExamsRoute: AppExamsRoute,
  AppFeesRoute: AppFeesRoute,
  AppFinalsRoute: AppFinalsRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppHealthRoute: AppHealthRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuarterResultsRoute: AppQuarterResultsRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppRecordRoute: AppRecordRoute,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSchemesRoute: AppSchemesRoute,
  AppSectionsRoute: AppSectionsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppSurveysRoute: AppSurveysRoute,
  AppTermRoute: AppTermRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppTimetableBuilderRoute: AppTimetableBuilderRoute,
  AppTimetableGridRoute: AppTimetableGridRoute,
  AppTransportRoute: AppTransportRoute,
  AppIndexRoute: AppIndexRoute,
  AppGuardiansGuardianIdRoute: AppGuardiansGuardianIdRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppTeachersInstructorIdRoute: AppTeachersInstructorIdRoute,
  AppGuardiansIndexRoute: AppGuardiansIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppTeachersIndexRoute: AppTeachersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MarksRoute: MarksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
